family.out : QuadraticProbing.o familyRunner.o familytree.o
	g++ -ansi -Wall -g -o family.out QuadraticProbing.o familyRunner.o familytree.o  

familyRunner.o : familyRunner.cpp familyRunner.h CPUTimer.h familytree.h 
	g++ -ansi -Wall -g -c familyRunner.cpp

QuadraticProbing.o : QuadraticProbing.cpp QuadraticProbing.h 
	g++ -ansi -Wall -g -c QuadraticProbing.cpp

familytree.o : familytree.cpp familytree.h 
	g++ -ansi -Wall -g -c familytree.cpp

clean : 
	rm -f family.out familyRunner.o StackAr.o QuadraticProbing.o QuadraticProbing2.o familytree.o
